type: config

status:
  class: receiver

config:
  properties:
    bar:
      type: string
    bool:
      type: boolean
    data_defined_elsewhere:
      $ref: http://example.com/schemas/external_schema.json#/properties/data
    foo:
      type: string
    my_special_embedded_field:
      type: string
    ptrStruct:
      type: object
    subconfig:
      allOf:
        - $ref: http://example.com/schemas/external_schema.json#/properties/data
      properties:
        bar:
          type: boolean
        foo:
          type: string
        sub_config2:
          properties:
            foobar:
              type: string
          type: object
      type: object
  type: object